name: Flake8 Linting

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Flake8 Lint
      uses: py-actions/flake8@v2
      with:
        max-line-length: '100'
        path: 'src'
        update-pip: true
